
export const basicEntIDs = {
  "t": 1,
  "u": 2,
  "f": 3,
  "r": 4,
  "r": 5,
  "8": 6,
  "h": 7,
  "j": 8,
  "classes": 13,
  "entities": 11,
  "workspaces": 17,
  "relations": 23,
  "qualities": 28,
  "relevancy qualities": 33,
  "relevancy qualities/format": 35,
  "predicate qualities": null,
  "relations/members": 59,
  "relations/subclasses": 58,
  "relations/relations": 55,
  "relations/relations for members": 51,
  "relations/sub-relations": 54,
  "relations/qualities": 49,
  "relations/qualities for members": 48,
  "relations/sub-qualities": 44,
};