
export const basicEntIDs = {
  "t": 1,
  "u": 2,
  "f": 3,
  "r": 4,
  "r": 5,
  "8": 6,
  "h": 7,
  "j": 8,
  "classes": 13,
  "entities": 11,
  "workspaces": 17,
  "relations": 28,
  "qualities": 31,
  "relevancy qualities": 35,
  "relevancy qualities/format": 37,
  "predicate qualities": null,
  "relations/members": 29,
  "relations/subclasses": 58,
  "relations/relations": 36,
  "relations/relations for members": 34,
  "relations/sub-relations": 33,
  "relations/qualities": 30,
  "relations/qualities for members": 23,
  "relations/sub-qualities": 53,
};