
export const basicEntIDs = {
  "t": 1,
  "u": 2,
  "f": 3,
  "r": 4,
  "r": 5,
  "8": 6,
  "h": 7,
  "j": 8,
  "classes": 23,
  "entities": 21,
  "workspaces": 28,
  "relations": 70,
  "qualities": 66,
  "relevancy qualities": 62,
  "relevancy qualities/format": 59,
  "predicate qualities": null,
  "relations/members": 71,
  "relations/subclasses": 68,
  "relations/relations": 63,
  "relations/relations for members": 40,
  "relations/sub-relations": 36,
  "relations/qualities": 64,
  "relations/qualities for members": 60,
  "relations/sub-qualities": 57,
};